apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ template "kafka-exporter.name" . }}
    release: {{ .Release.Name | quote }}
spec:
  ports:
    - port: {{ .Values.exporter.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "kafka-exporter.name" . }}
    release: {{ .Release.Name | quote }}
