apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: {{ include "kafka-exporter.name" . }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ .Release.Name }}
    release: prometheus-op
  name: {{ include "kafka-exporter.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "kafka-exporter.name" . }}
      release: {{ .Release.Name | quote }}
